# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.2.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"
